server:
  port: 8084

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
    web-application-type: reactive
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**


        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/user/**, /api/v1/roles/**
          filters:
            - AuthFilter


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka




